<?php

/**
 * @file
 * Contains contact_form_preview_remover.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function contact_form_preview_remover_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the contact_form_preview_remover module.
    case 'help.page.contact_form_preview_remover':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is a small custom module which removes the &quot;Review&quot; button from Drupal contact forms') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function contact_form_preview_remover_theme() {
  return [
    'contact_form_preview_remover' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function contact_form_preview_remover_form_alter(&$form, $form_state, $form_id) {

  // Look for any form provided by the contact module.
  // If you need to target a specific form, use complete form ID
  // (e.g. "Contact us" = 'contact_message_contact_form').
  if (strpos($form_id, 'contact_message_') !== FALSE) {
    $form['actions']['preview']['#access'] = FALSE;
  }
}
